sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install pybuilder coveralls
  - pyb -v install_dependencies
script:
  - pyb -v -X verify analyze
after_success:
  - coveralls --verbose
